/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ArrowRight, Building2, FileText, Handshake, HeartHandshake, Landmark, ShieldCheck } from "lucide-react";

const hero = "https://lh3.googleusercontent.com/aida/AP1WRLvG7IxyU0YTJ4OT7E5M1gQU0YidAzL2-fRXf0tzZj5kNA941d1lNwPX7WqicGd7rDP0tsgfNc_K2mMLIGk0Yx54wMAn-cpVhZ4oG2i2wcSEAAv233GCZHwN1epTbZIOAnG-_m-dwN26kJEpUNNgKj_CK6sGbKIhIYHo50vEXSYwe5xrCI-VonxmMA7FmyYHav-u8s1Zpv7Sk7mBWwu6aQb56oaOF4vWZyZgoh1wNGlSNxb8eOyR_K7R3u4";
const mission = "https://lh3.googleusercontent.com/aida/AP1WRLsJZB0evwHapUcpNeroMAVj9xnzLxFHAN_TicWVO92Jeduziwgzuz-lS0W_-TLL9-ZgGnpBwj5AtTVQz5GVZsJW6feF-Uymvrf8Qyk4bzX--kqNE4Z0nChQL8snQBicjXwCdGPvwYBuIjDXTDaTQTRKhNuh0dAhG8oet710BheaO-aEec3DBrY0thwyzwIyADmcjnn2K79FwVwTx5c_cuoTV1_O4tDeMx--Ia1KHF2fQlLnXOwH9TnABq4m";
const building = "https://lh3.googleusercontent.com/aida/AP1WRLvT0VZZzf1TZtKKX8yP-tqQPRYxr60bQB8HQmKEG7cWSDiHp-D5KCLddgREgoxS-T8wLDaDFwStZyh68zTO51caYQ834h_IWPBb5O9bkkn4tGnFytPyCHBAey5shLYEE9rv_1c0vV1aZT_o7Q2I73yvidfGnzPNW58CW5Y3rlkdSRpDQm5pfC7FlHiJ8sma2q3abAKYL1VEB5Ma2SfEeK_XJw2yfW0I873dOER0W3_EFJnC985WT43vKUyg";
const community = "https://lh3.googleusercontent.com/aida/AP1WRLugMgyZNGSfNH8F-Cf12FojjXBa2M6cK0gvQ5U1UleO-juawkUmTTyPJr2l6VNVpq9MUzCrMi3NlRj_ZgSHdwYevbXrzAWE1FU_335F0g0UuzhB8Z0SAm3KlklY2UdD3q_NLPsOiNiwRs0ZtJ2rxZ0xY462rlTKXLTfmbE239gxRaIWFFjIB4KFvjeM8mOlbYxc5IWLaCqhyAVDldwCohEt20jj6sCghrNUwW_7fHaAjT_KHZHaB1rYIJJl";

const timeline = [
  ["FASE 01 — CONCEPÇÃO", "Idealização do Projeto Vida Plena", "Definição da visão, dos valores e do modelo institucional."],
  ["FASE 02", "Constituição e governança", "Estruturação jurídica, administrativa e ética."],
  ["FASE 03", "Pesquisa e viabilidade", "Validações técnicas, territoriais e financeiras."],
  ["FASE 04", "Projeto arquitetônico", "Desenvolvimento do anteprojeto e projetos complementares."],
  ["FASES 05–13", "Licenças, mobilização, construção e equipagem", "Execução condicionada às aprovações e aos recursos necessários."],
  ["FASE 14", "Acolhimento dos primeiros moradores", "Início das atividades após todas as autorizações aplicáveis."],
];

export default function HomePage() {
  return <>
    <section id="inicio" className="relative flex min-h-[760px] items-end overflow-hidden pt-20 text-white md:min-h-screen md:items-center">
      <img src={hero} alt="Pessoa idosa acolhida com afeto" className="absolute inset-0 h-full w-full object-cover" />
      <div className="absolute inset-0 bg-gradient-to-r from-brand-deepDark/85 via-brand-deepDark/45 to-transparent" />
      <div className="editorial-shell relative z-10 w-full pb-20 pt-36 md:pb-0"><div className="max-w-3xl">
        <span className="editorial-label mb-5 block !text-white/75">Projeto social de inspiração cristã</span>
        <h1 className="font-serif text-[clamp(3rem,7vw,5.5rem)] font-semibold leading-[1.02] tracking-[-.035em] text-white">Envelhecer com dignidade também é um ato de amor.</h1>
        <p className="mt-8 max-w-2xl text-lg leading-8 text-white/90">O Instituto Vida Plena nasceu de uma convicção cristã de que as pessoas idosas merecem envelhecer com dignidade, amparo e amor em ação.</p>
        <div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/o-projeto" className="bg-brand-deep px-8 py-4 text-center text-xs font-semibold uppercase tracking-[.12em] text-white">Conheça o projeto</Link><Link href="/participe" className="border border-white px-8 py-4 text-center text-xs font-semibold uppercase tracking-[.12em] text-white hover:bg-white hover:text-brand-deep">Como participar</Link></div>
      </div></div>
    </section>

    <section className="editorial-section bg-brand-cream" id="missao"><div className="editorial-shell grid items-center gap-16 md:grid-cols-12">
      <div className="md:col-span-5"><span className="editorial-label mb-5 block">Valores & essência</span><h2 className="editorial-title mb-8">Nossa missão é restaurar a esperança.</h2><div className="space-y-6 editorial-copy"><p>A velhice não deve ser um período de solidão ou invisibilidade, mas um capítulo de plenitude, pertencimento e respeito.</p><p>O projeto propõe um ambiente em que o cuidado físico se una ao amparo espiritual e emocional, honrando a história e a individualidade de cada pessoa.</p></div><div className="mt-10 grid grid-cols-2 border-t editorial-rule pt-8"><div><strong className="block font-serif text-3xl font-medium text-brand-deep">Integral</strong><span className="editorial-label mt-2 block">Cuidado</span></div><div><strong className="block font-serif text-3xl font-medium text-brand-deep">Solidário</strong><span className="editorial-label mt-2 block">Propósito</span></div></div></div>
      <div className="relative md:col-start-7 md:col-span-6"><img src={mission} alt="Gesto de cuidado entre duas pessoas" className="aspect-[4/5] w-full object-cover" /><blockquote className="bg-brand-cream p-7 font-serif text-xl italic text-brand-deep lg:absolute lg:-bottom-8 lg:-left-8 lg:max-w-xs">“O cuidado é a linguagem mais profunda do amor.”</blockquote></div>
    </div></section>

    <section className="editorial-section bg-brand-sageLight" id="como-sera"><div className="editorial-shell"><div className="mx-auto mb-16 max-w-3xl text-center"><span className="editorial-label mb-5 block">Infraestrutura de excelência</span><h2 className="editorial-title">Um refúgio de paz projetado para o bem-estar.</h2></div><div className="relative min-h-[600px] overflow-hidden"><img src={building} alt="Referência conceitual de arquitetura integrada à natureza" className="absolute inset-0 h-full w-full object-cover" /><div className="relative ml-auto mt-72 max-w-lg border-l-4 border-brand-wood bg-white p-10 md:mr-12"><h3 className="mb-5 font-serif text-3xl font-medium text-brand-deep">Conforto e dignidade</h3><p className="editorial-copy">A proposta arquitetônica prioriza acessibilidade, iluminação natural, áreas verdes e espaços de convivência sem aparência hospitalar.</p><div className="mt-7 space-y-3 text-sm text-brand-charcoal"><p>— Suítes adaptadas</p><p>— Ambientes de saúde e reabilitação</p><p>— Espaços de espiritualidade e convivência</p></div><Link href="/como-sera" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-brand-deep">Conheça a proposta <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>

    <section className="editorial-section bg-brand-cream" id="transparencia"><div className="editorial-shell grid gap-12 border-y editorial-rule py-14 md:grid-cols-3">
      <div><Landmark className="mb-6 h-8 w-8 stroke-1 text-brand-wood"/><h3 className="mb-4 font-serif text-2xl font-medium">Governança ética</h3><p className="text-sm leading-7 text-brand-charcoal/75">Estrutura profissional, responsabilidades definidas e controle institucional.</p></div>
      <div><FileText className="mb-6 h-8 w-8 stroke-1 text-brand-wood"/><h3 className="mb-4 font-serif text-2xl font-medium">Informações abertas</h3><p className="text-sm leading-7 text-brand-charcoal/75">Documentos, avanços, limitações e decisões apresentados com clareza.</p></div>
      <div><ShieldCheck className="mb-6 h-8 w-8 stroke-1 text-brand-wood"/><h3 className="mb-4 font-serif text-2xl font-medium">Compromisso social</h3><p className="text-sm leading-7 text-brand-charcoal/75">Nenhuma promessa de operação, parceria ou captação antes da regularização necessária.</p></div>
    </div></section>

    <section className="editorial-section bg-brand-creamDark/70"><div className="editorial-shell"><h2 className="mb-16 text-center font-serif text-4xl font-medium">Jornada de implementação</h2><div className="relative mx-auto max-w-4xl border-l border-brand-deep/20 pl-10"><div className="space-y-12">{timeline.map(([phase,title,text]) => <div key={phase} className="timeline-node relative"><span className="editorial-label mb-2 block">{phase}</span><h3 className="font-serif text-2xl font-medium">{title}</h3><p className="mt-2 text-sm text-brand-charcoal/65">{text}</p></div>)}</div><Link href="/etapas" className="mt-12 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-brand-deep">Ver todas as etapas <ArrowRight className="h-4 w-4" /></Link></div></div></section>

    <section className="editorial-section bg-brand-cream" id="participar"><div className="editorial-shell grid items-center gap-20 lg:grid-cols-2"><div className="relative"><img src={community} alt="Comunidade reunida em ambiente acolhedor" className="aspect-square w-full object-cover"/><span className="absolute -right-10 -top-10 hidden h-40 w-40 border border-brand-wood/30 lg:block"/></div><div><span className="editorial-label mb-5 block">Seja um parceiro</span><h2 className="editorial-title mb-10">Sua participação ajuda a construir um legado de amor.</h2>
      <Link href="/participe" className="group block border-b editorial-rule py-6"><div className="flex items-center justify-between"><span className="flex items-center gap-4"><HeartHandshake className="h-5 w-5 text-brand-wood"/><strong className="font-serif text-2xl font-medium text-brand-deep">Manifestação de interesse</strong></span><ArrowRight className="h-5 w-5 text-brand-wood"/></div><p className="mt-3 text-sm text-brand-charcoal/65">Pessoas que desejam acompanhar, apoiar ou colaborar com o projeto.</p></Link>
      <Link href="/participe" className="group block border-b editorial-rule py-6"><div className="flex items-center justify-between"><span className="flex items-center gap-4"><Building2 className="h-5 w-5 text-brand-wood"/><strong className="font-serif text-2xl font-medium text-brand-deep">Conhecimento especializado</strong></span><ArrowRight className="h-5 w-5 text-brand-wood"/></div><p className="mt-3 text-sm text-brand-charcoal/65">Profissionais das áreas jurídica, contábil, assistencial, arquitetônica e social.</p></Link>
      <Link href="/participe" className="group block border-b editorial-rule py-6"><div className="flex items-center justify-between"><span className="flex items-center gap-4"><Handshake className="h-5 w-5 text-brand-wood"/><strong className="font-serif text-2xl font-medium text-brand-deep">Parcerias institucionais</strong></span><ArrowRight className="h-5 w-5 text-brand-wood"/></div><p className="mt-3 text-sm text-brand-charcoal/65">Organizações alinhadas à missão e aos princípios de transparência.</p></Link>
    </div></div></section>

    <section className="editorial-section bg-brand-sageLight"><div className="editorial-shell max-w-3xl"><h2 className="mb-12 text-center font-serif text-4xl font-medium">Perguntas frequentes</h2>{[["O Instituto já está funcionando?","Ainda não. O Instituto Vida Plena está em fase de planejamento, pesquisa e estruturação."],["Existe alguma captação financeira ativa?","Não. Qualquer futura mobilização financeira dependerá da constituição jurídica, de conta institucional e dos controles de governança."],["O atendimento será restrito a uma denominação religiosa?","Não. A inspiração é cristã, mas o acolhimento previsto respeita a dignidade e a liberdade de cada pessoa."]].map(([q,a]) => <details key={q} className="group border-b editorial-rule py-5"><summary className="cursor-pointer list-none font-serif text-xl text-brand-deep">{q}<span className="float-right text-brand-wood">+</span></summary><p className="mt-4 pr-8 text-sm leading-7 text-brand-charcoal/70">{a}</p></details>)}<div className="mt-10 text-center"><Link href="/perguntas-frequentes" className="text-xs font-semibold uppercase tracking-[.12em] text-brand-deep">Ver todas as perguntas</Link></div></div></section>
  </>;
}
